setup github actions
Automattic/WPCOM-Legacy-Redirector pull request #106
Opened 2021-06-05 05:05 UTC by trepmal

migrates from travis to github actions

2021-06-15 10:16 UTC, GaryJones requested changes
See https://github.com/Automattic/msm-sitemap/pull/166#pullrequestreview-683774018 for feedback.

2021-06-18 23:34 UTC, GaryJones approved these changes
One suggested change, but otherwise LGTM, so approving.

2021-06-18 23:34 UTC, GaryJones commented on .phpcs.xml.dist
> +	<config name="minimum_supported_wp_version" value="5.5"/>
```suggestion
	<config name="minimum_supported_wp_version" value="4.5"/>
```

2021-06-18 23:35 UTC, GaryJones commented on composer.json
> +		"coverage": [
Looks like `coverage-ci` script is missing (tests failing on PHP 8.0 job).

2021-06-19 12:00 UTC, GaryJones approved these changes

2021-06-25 21:34 UTC, trepmal commented
The required status check must be removed. If I'm looking at the options correct, we'll probably want to replace it with at least a few of the new checks (each WP+PHP combination from the matrix is its own)

2021-10-15 13:08 UTC, GaryJones commented
> The required status check must be removed.

Done. Once the PR is rebased to fix the conflict, the entry for the travis-ci job requirement will disappear.

>  If I'm looking at the options correct, we'll probably want to replace it with at least a few of the new checks (each WP+PHP combination from the matrix is its own)

Agreed - these can be all of them, and can be added once the workflows are merged.

2024-05-22 13:36 UTC, GaryJones commented
Handled with #127, #128, #129, #130.

2024-05-22 13:36 UTC, closed without merging